image: node

cache:
  paths:
    - node_modules/


before_script:
  - mkdir -p ~/.ssh
  - (echo "$SSH_PRIVATE_KEY" | base64 -d) | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H '178.170.47.43' >> ~/.ssh/known_hosts


deployToTest:
  stage: deploy
  environment:
    name: dev0.dequity
    url: dev0.dequity.io
  script:
    - bash deploy-scripts/deploy-test-script.sh
  only:
    - dev0
