export const TOGGLE_MENU = "TOGGLE_MENU";
export const TOGGLE_MODAL_EMAIL_SHOW = "TOGGLE_MODAL_EMAIL_SHOW";
export const TOGGLE_MODAL_THANKS_SHOW = "TOGGLE_MODAL_THANKS_SHOW";
export const TOGGLE_APP_THEME = "TOGGLE_APP_THEME";
export const CHANGE_APP_LANGUAGE = "CHANGE_APP_LANGUAGE";
export const TOGGLE_SCROLL_TO_HOW = "TOGGLE_SCROLL_TO_HOW";

export const HOME_FETCH = "HOME_FETCH";
export const HOME_LOADING = "HOME_LOADING";
export const HOME_SUCCESS = "HOME_SUCCESS";
export const HOME_FAILED = "HOME_FAILED";

export const ABOUT_FETCH = "ABOUT_FETCH";
export const ABOUT_LOADING = "ABOUT_LOADING";
export const ABOUT_SUCCESS = "ABOUT_SUCCESS";
export const ABOUT_FAILED = "ABOUT_FAILED";

export const FAQS_FETCH = "FAQS_FETCH";
export const FAQS_LOADING = "FAQS_LOADING";
export const FAQS_SUCCESS = "FAQS_SUCCESS";
export const FAQS_FAILED = "FAQS_FAILED";

export const FAQSMenu_FETCH = "FAQSMenu_FETCH";
export const FAQSMenu_LOADING = "FAQSMenu_LOADING";
export const FAQSMenu_SUCCESS = "FAQSMenu_SUCCESS";
export const FAQSMenu_FAILED = "FAQSMenu_FAILED";

export const MARKETPLACE_FETCH = "MARKETPLACE_FETCH";
export const MARKETPLACE_LOADING = "MARKETPLACE_LOADING";
export const MARKETPLACE_SUCCESS = "MARKETPLACE_SUCCESS";
export const MARKETPLACE_FAILED = "MARKETPLACE_FAILED";