export * from './HomePageNew'
export * from './AboutPage'
export * from './FAQPage'
export * from './PropertyPage'
export * from './MarketPage'
export * from './PaymentPage'
export * from './LearnPage'
export * from './ResearchPage'